-- Internal 组件（astronverse-internal）：原子元数据（需在已有库执行时合并进 atomCommon，见 init 脚本或下方说明）
-- 说明：左侧原子树来自 atom_key = atomCommon 的 JSON（atomicTree / atomicTreeExtend），
-- 仅插入本表其它行不会出现菜单；必须同步更新 atomCommon（见下方 UPDATE）。
-- robot-service 对个人版租户会隐藏 enterprise 相关节点，与 Internal 分组无关。

INSERT INTO `c_atom_meta_new` (`atom_key`,`atom_content`,`sort`,`create_time`,`update_time`) VALUES ('Internal.wecom_group_message','{"key": "Internal.wecom_group_message","title": "企业微信群消息","version": "1.0.0","src": "astronverse.internal.internal.Internal().wecom_group_message","comment": "向机器人地址(@{robot_url})发送文本(@{content})，@某人手机号(@{mentioned_mobile})，响应保存至(@{response_text})","inputList": [{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "robot_url","title": "机器人地址","name": "robot_url","tip": "企业微信群机器人的 Webhook 地址","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "content","title": "文本内容","name": "content","tip": "消息正文","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "mentioned_mobile","title": "@某人（手机号）","name": "mentioned_mobile","tip": "需要 @ 的用户手机号，多个用英文逗号分隔，如 15563371738,13800138000","default": "","value": [{"type": "str","value": ""}],"required": false}],"outputList": [{"types": "Str","formType": {"type": "RESULT"},"key": "response_text","title": "响应内容","tip": "接口返回的文本结果"}],"icon": "wecom-robot-message","helpManual": "向企业微信群机器人 Webhook 发送 text 消息；多个手机号用英文逗号分隔。"}',NULL,NOW(),NOW()) ON DUPLICATE KEY UPDATE `atom_content`=VALUES(`atom_content`),`update_time`=NOW();
INSERT INTO `c_atom_meta_new` (`atom_key`,`atom_content`,`sort`,`create_time`,`update_time`) VALUES ('Internal.yunshang_lunan_message','{"key": "Internal.yunshang_lunan_message","title": "云上鲁南消息推送","version": "1.0.0","src": "astronverse.internal.internal.Internal().yunshang_lunan_message","comment": "向接口(@{url})推送消息，接收方(@{receiver_id})，标题(@{title})，正文(@{text})，响应保存至(@{response_text})","inputList": [{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "url","title": "接口地址","name": "url","tip": "云上鲁南接口 URL，可填写占位变量或配置参数，例如 ${YUNSHANG_LUNAN_API_URL}","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "receiver_id","title": "接收方 ID","name": "receiver_id","tip": "receiver_id，接收方标识","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "text","title": "正文","name": "text","tip": "text，消息正文","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "title","title": "标题","name": "title","tip": "title，消息标题","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "nonce","title": "nonce","name": "nonce","tip": "请求随机串，按接口要求填写","default": "","value": [{"type": "str","value": ""}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "token","title": "token","name": "token","tip": "鉴权 token","default": "","value": [{"type": "str","value": ""}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "msg_type","title": "msg_type","name": "msg_type","tip": "消息类型，按接口要求填写","default": "","value": [{"type": "str","value": ""}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "sender_id","title": "sender_id","name": "sender_id","tip": "发送方 ID","default": "","value": [{"type": "str","value": ""}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "link","title": "link","name": "link","tip": "链接字段，可为空","default": "","value": [{"type": "str","value": ""}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "sign","title": "sign","name": "sign","tip": "签名，按接口要求填写","default": "","value": [{"type": "str","value": ""}],"required": false}],"outputList": [{"types": "Str","formType": {"type": "RESULT"},"key": "response_text","title": "响应内容","tip": "接口返回的文本结果"}],"icon": "cloud-lunan-message","helpManual": "接口 URL 请填写实际地址或使用流程变量占位；nonce、token、msg_type、sender_id、link、sign 等按对接文档填写或绑定变量。"}',NULL,NOW(),NOW()) ON DUPLICATE KEY UPDATE `atom_content`=VALUES(`atom_content`),`update_time`=NOW();
-- 在「扩展原子」页签展示分组：向 atomCommon.atomicTreeExtend 首部插入 internal 分组（与仓库 init 中片段一致）。
-- 仅当库中 atomCommon 仍为旧版（atomicTreeExtend 以 AI 开头）时执行；若已包含 internal 请勿重复执行。
UPDATE `c_atom_meta_new` SET `atom_content` = REPLACE(
  `atom_content`,
  'atomicTreeExtend": [{"key": "ai", "title": "AI", "atomics":',
  'atomicTreeExtend": [{"key": "internal", "title": "\\u5185\\u90e8\\u7ec4\\u4ef6", "atomics": [{"key": "Internal.wecom_group_message", "title": "\\u4f01\\u4e1a\\u5fae\\u4fe1\\u7fa4\\u6d88\\u606f", "icon": "wecom-robot-message"}, {"key": "Internal.yunshang_lunan_message", "title": "\\u4e91\\u4e0a\\u9c81\\u5357\\u6d88\\u606f\\u63a8\\u9001", "icon": "cloud-lunan-message"}]}, {"key": "ai", "title": "AI", "atomics":'
), `update_time` = NOW()
WHERE `atom_key` = 'atomCommon'
  AND `atom_content` LIKE '%atomicTreeExtend": [{"key": "ai", "title": "AI", "atomics":%'
  AND `atom_content` NOT LIKE '%"key": "internal"%';

-- 修复：此前将 key 前缀改为 Internal 时误把分组显示名 title 也改成了英文，此处恢复为「内部组件」
UPDATE `c_atom_meta_new` SET `atom_content` = REPLACE(
  `atom_content`,
  '"key": "internal", "title": "Internal", "atomics":',
  '"key": "internal", "title": "\\u5185\\u90e8\\u7ec4\\u4ef6", "atomics":'
), `update_time` = NOW()
WHERE `atom_key` = 'atomCommon'
  AND `atom_content` LIKE '%"key": "internal", "title": "Internal", "atomics":%';

