-- Internal 组件（astronverse-internal）：原子元数据（需在已有库执行时合并进 atomCommon，见 init 脚本或下方说明）
-- 说明：左侧原子树来自 atom_key = atomCommon 的 JSON（atomicTree / atomicTreeExtend），
-- 仅插入本表其它行不会出现菜单；必须同步更新 atomCommon（见下方 UPDATE）。
-- robot-service 对个人版租户会隐藏 enterprise 相关节点，与 Internal 分组无关。

INSERT INTO `c_atom_meta_new` (`atom_key`,`atom_content`,`sort`,`create_time`,`update_time`) VALUES ('Internal.wecom_group_message','{"key": "Internal.wecom_group_message","title": "企业微信群消息","version": "1.0.0","src": "astronverse.internal.internal.Internal().wecom_group_message","comment": "向机器人地址(@{robot_url})发送文本(@{content})，@某人手机号(@{mentioned_mobile})，响应保存至(@{response_text})","inputList": [{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "robot_url","title": "机器人地址","name": "robot_url","tip": "企业微信群机器人的 Webhook 地址","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "content","title": "文本内容","name": "content","tip": "消息正文","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "mentioned_mobile","title": "@某人（手机号）","name": "mentioned_mobile","tip": "需要 @ 的用户手机号，多个用英文逗号分隔，如 15563371738,13800138000","default": "","value": [{"type": "str","value": ""}],"required": false}],"outputList": [{"types": "Str","formType": {"type": "RESULT"},"key": "response_text","title": "响应内容","tip": "接口返回的文本结果"}],"icon": "wecom-robot-message","helpManual": "向企业微信群机器人 Webhook 发送 text 消息；多个手机号用英文逗号分隔。"}',NULL,NOW(),NOW()) ON DUPLICATE KEY UPDATE `atom_content`=VALUES(`atom_content`),`update_time`=NOW();
INSERT INTO `c_atom_meta_new` (`atom_key`,`atom_content`,`sort`,`create_time`,`update_time`) VALUES ('Internal.yunshang_lunan_message','{"key": "Internal.yunshang_lunan_message","title": "云上鲁南消息推送","version": "1.0.0","src": "astronverse.internal.internal.Internal().yunshang_lunan_message","comment": "由服务端转发至云上鲁南接口，接收方(@{receiver_id})，类型(@{msg_type})，响应保存至(@{response_text})","inputList": [{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "receiver_id","title": "接收方工号","name": "receiver_id","tip": "receiver_id，接收方工号","default": "","value": [{"type": "str","value": ""}],"required": true},{"types": "YunshangLunanMsgType","formType": {"type": "RADIO"},"key": "msg_type","title": "消息类型","name": "msg_type","tip": "Text 为文本消息需填写正文；File 为文件消息需填写链接并在 text 中传文件信息 JSON","options": [{"label": "Text（文本）","value": "Text"},{"label": "File（文件）","value": "File"}],"default": "Text","required": true},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "text","title": "消息内容","name": "text","tip": "Text 时填写正文；File 时填写 {\"fileName\":\"file_name\",\"fileSize\":\"file_size\"}","default": "","value": [{"type": "str","value": ""}],"dynamics": [{"key": "$this.text.show","expression": "return $this.msg_type.value == ''Text''"}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "link","title": "附件链接","name": "link","tip": "msg_type 为 File 时填写","default": "","value": [{"type": "str","value": ""}],"dynamics": [{"key": "$this.link.show","expression": "return $this.msg_type.value == ''File''"}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "file_name","title": "文件名","name": "file_name","tip": "msg_type 为 File 时填写，系统会封装进 text 的 fileName","default": "","value": [{"type": "str","value": ""}],"dynamics": [{"key": "$this.file_name.show","expression": "return $this.msg_type.value == ''File''"}],"required": false},{"types": "Str","formType": {"type": "INPUT_VARIABLE_PYTHON"},"key": "file_size","title": "文件大小","name": "file_size","tip": "msg_type 为 File 时填写，系统会封装进 text 的 fileSize","default": "","value": [{"type": "str","value": ""}],"dynamics": [{"key": "$this.file_size.show","expression": "return $this.msg_type.value == ''File''"}],"required": false}],"outputList": [{"types": "Str","formType": {"type": "RESULT"},"key": "response_text","title": "响应内容","tip": "接口返回的文本结果"}],"icon": "cloud-lunan-message","helpManual": "接口地址、token、AES 密钥、签名等在后端环境变量配置；Text 消息填写正文；File 消息填写链接、文件名、文件大小，系统会将文件信息封装到 text 字段。"}',NULL,NOW(),NOW()) ON DUPLICATE KEY UPDATE `atom_content`=VALUES(`atom_content`),`update_time`=NOW();
-- 在「扩展原子」页签展示分组：向 atomCommon.atomicTreeExtend 首部插入 internal 分组（与仓库 init 中片段一致）。
-- 仅当库中 atomCommon 仍为旧版（atomicTreeExtend 以 AI 开头）时执行；若已包含 internal 请勿重复执行。
UPDATE `c_atom_meta_new` SET `atom_content` = REPLACE(
  `atom_content`,
  'atomicTreeExtend": [{"key": "ai", "title": "AI", "atomics":',
  'atomicTreeExtend": [{"key": "internal", "title": "\\u5185\\u90e8\\u7ec4\\u4ef6", "atomics": [{"key": "Internal.wecom_group_message", "title": "\\u4f01\\u4e1a\\u5fae\\u4fe1\\u7fa4\\u6d88\\u606f", "icon": "wecom-robot-message"}, {"key": "Internal.yunshang_lunan_message", "title": "\\u4e91\\u4e0a\\u9c81\\u5357\\u6d88\\u606f\\u63a8\\u9001", "icon": "cloud-lunan-message"}]}, {"key": "ai", "title": "AI", "atomics":'
), `update_time` = NOW()
WHERE `atom_key` = 'atomCommon'
  AND `atom_content` LIKE '%atomicTreeExtend": [{"key": "ai", "title": "AI", "atomics":%'
  AND `atom_content` NOT LIKE '%"key": "internal"%';

-- 修复：此前将 key 前缀改为 Internal 时误把分组显示名 title 也改成了英文，此处恢复为「内部组件」
UPDATE `c_atom_meta_new` SET `atom_content` = REPLACE(
  `atom_content`,
  '"key": "internal", "title": "Internal", "atomics":',
  '"key": "internal", "title": "\\u5185\\u90e8\\u7ec4\\u4ef6", "atomics":'
), `update_time` = NOW()
WHERE `atom_key` = 'atomCommon'
  AND `atom_content` LIKE '%"key": "internal", "title": "Internal", "atomics":%';

